#
# minicargo overrides file
#

# rustc needs rustc's libproc_macro (not mrustc's)
[add.'compiler/rustc_expand'.dependencies]
proc_macro = { path = "../../library/proc_macro" }
[add.'compiler/rustc_builtin_macros'.dependencies]
proc_macro = { path = "../../library/proc_macro" }
[add.'compiler/rustc_metadata'.dependencies]
proc_macro = { path = "../../library/proc_macro" }

# Add an exact version of `regex` to account for there being two versions in the `vendor` dir
# - The higher one depends on a version of of `aho-corasick` that isn't vendored
[add.'compiler/rustc_driver'.dependencies]
regex = "=1.4.3"
[add.'tools/cargo'.dependencies]
regex = "=1.4.3"

[add.'library/std'.dependencies.compiler_builtins]
features = ["no-asm"]
[add.'library/panic_unwind'.dependencies.compiler_builtins]
features = ["no-asm"]


[delete]
# Allow rustc's libproc_macro to build by removing the std dependency (it's built during rustc build, not during std build)
'library/proc_macro' = [
	"dependencies.std",
	]
# mrustc has already built a proc_macro, remove it from libtest's deps (used on linux)
'library/test' = [
	"dependencies.proc_macro",
	]
